### ISSUE TITLE
EIP-1559 model: "demand always exceeds supply" should not be excluded

### ISSUE THREAD

**Issue by veox** [ethereum/rig#4]
... in the "bottomless pit" scenario, with the reason:

> (...) our model would quickly blow up. Unless we introduce some kind of staling, our mempool would soon be overloaded.

However, this is exactly the case on real networks: there is no _mempool_ as far as the protocol is concerned; nodes are constantly bombarded with transactions, and handle their _txpool_ with various degree of disgrace.

In other words, the true "bottomless pit" scenario will take this into account, especially for scenarios of long-term congestion (as is currently the case on main-net, BTW).

Below are a few modifications to that section to simulate this. This is all in `eip1559.ipynb`.

-----

First, `timesteps` is increased (this proved [somewhat useful while toying around](https://www.reddit.com/r/ethereum/comments/gd6kc3/a_great_faq_for_the_eip_1559_from_vitalik/fqhh5ka/)). the oscillation period is increased to produce less noise, and - most importantly - a `log` component is introduced that immediately overshoots capacity:

``` python
from math import log, sin, pi

timesteps = 600

def generate_oscillating_scenario(timesteps):
    return [int(400 + 200 * sin(i * pi / 96.0) + int(100 * log(i+1))) for i in range(timesteps)]
```

![i1](https://user-images.githubusercontent.com/3036030/81827241-3f8f7300-9541-11ea-9ac5-bc1d08c034e6.png)

Then, transaction pool limiting is introduced, as well as a dependence of `gas_premium` on `timestep` (sorry for the hackishness on both):

``` python
# NOTE: geth defaults to txpool size of 4096, not 8192
def update_demand_scenario(timestep, demand, tx_scenario, txpool_size=8192):
    for i in range(tx_scenario[timestep]):
        # TODO: dependence of `gas_premium` on existing `demand`, not just `timestep`
        gas_premium = uniform(1, 10 + timestep) * (10 ** 9)
    # ... the rest of the loop is unmodified

    # txpool strategy: retain txs with highest `fee_cap`
    sorted_demand = sorted(
        [(tx_hash, tx) for tx_hash, tx in demand.items()],
        key = lambda tuple_: tuple_[1].fee_cap,
        reverse=True,
    )
    trimmed_demand = sorted_demand[:txpool_size]
    demand = {tuple_[0]: tuple_[1] for tuple_ in trimmed_demand}
    
    return demand
```

That's it! This produces:

![i2](https://user-images.githubusercontent.com/3036030/81828606-a2cdd500-9542-11ea-8701-6049ba86350d.png)

![i3](https://user-images.githubusercontent.com/3036030/81828617-a5302f00-9542-11ea-80ec-5a576aa9cddd.png)

![i4](https://user-images.githubusercontent.com/3036030/81828623-a7928900-9542-11ea-9875-d859865bbaf2.png)

(~~Slightly unexpectedly~~ Reducing the dependence of `gas_premium` on `timestep` to a tenth of that shown, and restoring the initial max to `11` instead of `10` (this was an accident):

``` python
gas_premium = uniform(1, 11 + timestep/10) * (10 ** 9)
```

... resulted in `basefee` going ~~even higher~~ lower, to > 4.5e10 instead of > 3.5e11.)

-----

This - modelling txpool saturation, especially with ever-increasing pressure - is important in face of the main critique of EIP-1559: namely, that it devolves into the current situation, and brings no benefit.

Of course, the above doesn't show the actual dynamic we observe. The demand distribution stays `uniform()`, starting with `[1, 11)` and ending with `[1, 611]` - in practice, we see the lower bound go up, too.

However, the rarely mentioned effect is: although the _average_ number of transactions fluctuates around `target_gas` or so, - that there _are_ fluctuations coinciding with peaks and valleys in demand, if demand doesn't go below `producer_limit`.

So, in fact, the situation does _not_ devolve into what we have currently. It's seemingly something worse.

This needs more modelling!

**Comment by veox** [comment]
To think of it, dependence of `gas_premium` on other existing demand can be achieved through `basefee` - that's quite likely how it's going to be implemented in wallet UIs (even if concealed from the average user):

``` python
def update_demand_scenario(timestep, demand, basefee, tx_scenario, txpool_size=8192):
    for i in range(tx_scenario[timestep]):
        gas_premium = basefee/2 + uniform(1 + timestep/100, 11 + timestep/10) * (10 ** 9)
        # ... the rest as previously
```

And, of course, during the `%%capture` step:

``` python
# ...
for timestep in range(T):
    demand = update_demand_scenario(timestep, demand, basefee, tx_scenario)
    # ...
```

Even with considerably less pool pressure:

``` python
def generate_oscillating_scenario(timesteps):
    return [int(400 + 200 * sin(i * pi / 96.0) + int(32 * log(i+1))) for i in range(timesteps)]
```

![a1](https://user-images.githubusercontent.com/3036030/81836043-9f8b1700-954b-11ea-8bf1-ae120853c498.png)

... we get this:

![a2](https://user-images.githubusercontent.com/3036030/81836071-ac0f6f80-954b-11ea-8b52-17ea2eeaa604.png)

![a3](https://user-images.githubusercontent.com/3036030/81836084-af0a6000-954b-11ea-8cfd-383e1d036f56.png)

![a4](https://user-images.githubusercontent.com/3036030/81836093-b0d42380-954b-11ea-84cb-a022a33717e5.png)

**Comment by barnabemonnot** [comment]
Hi @veox ! Thanks for the comments, yeah you are totally right. It was very much on purpose that I steered clear of modelling any kind of smart users who would set their premiums based on the current demand, or smart miners who organised their tx pool (or even had smarter policies on including transactions). I've only hinted at it in several places of the notebook, but was more interested in a first approach at the dynamics of the mechanism itself. I don't think they are that well-understood, even though they are "simple". I get that the worry is in the high congestion case, but even in the extreme spiking demand case I show the basefee really quickly increases to raise to that price. I could stress this more by referring to actual time in seconds rather than the more abstract "steps".

Also, from the basefee update rule's point of view, demand is demand, so introducing a "Tx" class and a "Block" class was somewhat of a red herring to motivate the discussion, but I could have simply plugged in a series of realised gas included in the block instead (that's a lot less tangible though).

The plan is to do another notebook with finer modelling, agreed that there are more open questions there, and you point out an important one. This will also be based on the current formal analysis that I am undertaking (see a premise [here](https://ethresear.ch/t/eip-1559-simulations/7280/3), which includes looking at user strategies as functions of the current basefee (though you could make the case that they could be more complex and depend on the current state of the txpool, or that this info is encapsulated by the wallet).

I had also not seen the Reddit discussion you linked, but thanks for pointing out the notebook and using it as a tool to model yourself! They are definitely more useful if they allow other people to use them as springboards to run their own models. I need to dig deeper into the results you present here too.
